parameters:
  ServiceConnection:

stages:
- stage: Build
  displayName: Build Image
  pool:
   vmImage: ubuntu-latest
  jobs:
  - job: Build_Image
    displayName: Build Image
    steps:
      - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

      - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
        parameters:
          ContainerRegistryName: $(PublicAcrName)
          ServiceConnection: ${{ parameters.ServiceConnection }}
          ImageName: das-logstash-exporter

      - pwsh: |
          cd integration-tests
          docker-compose up --detach
          Start-Sleep -Seconds 20 # do better
          $MetricsResponse = Invoke-RestMethod "http://localhost:9198/metrics"
          $RequiredMetrics = $MetricsResponse -like "*logstash_node_queue_size_bytes*"
          if(!$RequiredMetrics){
            throw "Required logstash metrics not available"
          }
        displayName: Integration Test
