go:
    cgo: false
    version: 1.18.2
repository:
    path: github.com/SkillsFundingAgency/das-logstash-exporter
build:
    binaries:
        - name: logstash_exporter
    flags: -mod=vendor -a -tags 'netgo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE

crossbuild:
    platforms:
        - linux/amd64
