resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SkillsFundingAgency

trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
- group: Release Management Resources

stages:
  - template: /pipeline-templates/stage/build.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
